name = "lapce-odin"
version = "0.0.1"
author = "Syntacti"
display-name = "Odin"
description = "Odin language lsp support"
wasm = "bin/lapce-odin.wasm"


[activation]
language = ["odin"]
workspace-contains = ["*/*.odin"]

[config."volt.serverPath"]
default = ""
description = "Path to ols"
